### PR TITLE
DCT-25515

### PR DESCRIPTION
**Pull request by joetsaij**
goes with /sunbirddcim/dctrack_app_client/pull/5609
Update jQuery dependency to 3.4.1 for visualsearch repo

### CODE REVIEW

**Comment by andrew-garland** [comment]
If this gets merged, does it immediately impact dctrack?

**Comment by joetsaij** [comment]
> If jquery is a dependency, why is vendor/jquery-3.4.1.js checked into our repo? Can we remove that file?

The dependencies.js is referenced by the core module visualsearch.js and it is bundled by rake (task runner) which refers to all files under vendor folder. So yes we could remove jquery-3.4.1.js file from vendor but then we need to manually copy-paste the new version jquery source code into dependencies.js instead of generating it via task runner.

**Comment by joetsaij** [comment]
> If this gets merged, does it immediately impact dctrack?

Yes, after merged, the next build of dctrack will got the visualsearch with 3.4.1 jQuery

**Comment by andrew-garland** [comment]
Can we configure it so that we have more control over it?  e.g. in dctrack refer to a tag/release?

**Comment by joetsaij** [comment]
Yes, we could add visualsearch version info to package.json to tell npm to use specific version of visualsearch. e.g. "visualsearch": "git+https://github.com/sunbirddcim/visualsearch.git#v1.0.0"
refer to https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by andrew-garland** [comment]
I created tag 1.0.0 of visual search.  please do a PR for app client in 7.1.0 branch to specifically use that version.

**Pull request merged**
