### PR TITLE
[8.1.0] DCT-25515 Update jquery used by visual search (to 3.5.1)

### PR DESCRIPTION
**Pull request by joetsaij**
goes with sunbirddcim/dctrack_app_client/pull/6534

Update :
jquery to 3.5.1
jquery-ui to 1.12.1

And test visualsearch in dctrack, it works in assets tab permission dialog, but not working in floormap search input box.
Still need to investigate why it does not work in floormap.
image

### CODE REVIEW

**Review by andrew-garland — COMMENTED** [review]
Did you test visual search in the data model sync page?

**Review by tppt — APPROVED** [review]

**Comment by joetsaij** [comment]
@andrew-garland ,
Yes, visualsearch works fine in data model sync even though it has the same error as floormap.
image

**Comment by joetsaij** [comment]
@andrew-garland ,
After some investigation and testing, I could make visualsearch works in floormap by turning off the autoFocus feature of autocomplete widget, but unluckily the console error is still there.
cc @davidhsieh , @tppt 
image

**Comment by andrew-garland** [comment]
@joetsaij Based on your findings so far, it is too risky for 8.0.0 

Deferring to 8.1.0

CC @davidhsieh  @tppt

**Comment by joetsaij** [comment]
@tppt , would you help to review and merge this PR ? Now the console error is fixed and visual search works fine on dcTrack with your branch DCT-26507 which also updates jQuery to 3.5.1 used by app client.
And this PR goes with sunbirddcim/dctrack_app_client/pull/6534 which fixes the css issue.

cc @davidhsieh , @andrew-garland , @snassoura

**Pull request merged**
